### ISSUE TITLE
Error when first time loading up

### ISSUE THREAD

**Issue by donmhico** [WebDevStudios/nextjs-wordpress-starter#218]
**Describe the bug**
After following the [Backend Setup wiki](https://github.com/WebDevStudios/nextjs-wordpress-starter/wiki/Backend-Setup) and the [Frontend Setup wiki](https://github.com/WebDevStudios/nextjs-wordpress-starter/wiki/Frontend-Setup), I get this error when running `npm run dev`.

```
TypeError: Object(...) is not a function
    at MyDocument.render (webpack-internal:///./pages/_document.js:14:99)
    at d (/Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:35:231)
    at bb (/Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
    at a.b.render (/Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
    at a.b.read (/Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
    at exports.renderToStaticMarkup (/Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:51:446)
    at renderDocument (/Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/next/dist/next-server/server/render.js:3:715)
    at renderToHTML (/Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/next/dist/next-server/server/render.js:56:103)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async /Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/next/dist/next-server/server/next-server.js:107:97
    at async /Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/next/dist/next-server/server/next-server.js:100:142
    at async DevServer.renderToHTMLWithComponents (/Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/next/dist/next-server/server/next-server.js:132:387)
    at async DevServer.renderErrorToHTML (/Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/next/dist/next-server/server/next-server.js:134:327)
    at async DevServer.renderErrorToHTML (/Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/next/dist/server/next-dev-server.js:34:1204)
    at async DevServer.renderToHTML (/Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/next/dist/next-server/server/next-server.js:133:1281)
TypeError: Object(...) is not a function
    at App (webpack-internal:///./pages/_app.js:137:123)
    at d (/Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
    at bb (/Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
    at a.b.render (/Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
    at a.b.read (/Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
    at exports.renderToString (/Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
    at Object.renderPage (/Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/next/dist/next-server/server/render.js:54:851)
    at Function.getInitialProps (webpack-internal:///./node_modules/next/dist/pages/_document.js:135:19)
    at loadGetInitialProps (/Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/next/dist/next-server/lib/utils.js:5:101)
    at renderToHTML (/Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/next/dist/next-server/server/render.js:54:1142)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async /Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/next/dist/next-server/server/next-server.js:107:97
    at async __wrapper (/Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/next/dist/lib/coalesced-function.js:1:330)
    at async DevServer.renderToHTMLWithComponents (/Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/next/dist/next-server/server/next-server.js:132:387)
    at async DevServer.renderToHTML (/Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/next/dist/next-server/server/next-server.js:133:522)
event - build page: /[...slug]
wait  - compiling...
event - compiled successfully
(node:22406) ExperimentalWarning: AbortController is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
TypeError: Object(...) is not a function
    at MyDocument.render (webpack-internal:///./pages/_document.js:14:99)
    at d (/Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:35:231)
    at bb (/Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
    at a.b.render (/Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
    at a.b.read (/Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
    at exports.renderToStaticMarkup (/Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:51:446)
    at renderDocument (/Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/next/dist/next-server/server/render.js:3:715)
    at renderToHTML (/Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/next/dist/next-server/server/render.js:56:103)
    at async /Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/next/dist/next-server/server/next-server.js:107:97
    at async /Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/next/dist/next-server/server/next-server.js:100:142
    at async DevServer.renderToHTMLWithComponents (/Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/next/dist/next-server/server/next-server.js:132:387)
    at async DevServer.renderErrorToHTML (/Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/next/dist/next-server/server/next-server.js:134:327)
    at async DevServer.renderErrorToHTML (/Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/next/dist/server/next-dev-server.js:34:1204)
    at async DevServer.renderToHTML (/Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/next/dist/next-server/server/next-server.js:133:1281)
    at async DevServer.renderToHTML (/Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/next/dist/server/next-dev-server.js:34:578)
    at async DevServer.render (/Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/next/dist/next-server/server/next-server.js:72:236)
Error: Response not successful: Received status code 500
    at new ApolloError (/Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/@apollo/client/errors/errors.cjs.js:31:28)
    at /Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/@apollo/client/core/core.cjs.js:1490:19
    at /Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/@apollo/client/utilities/utilities.cjs.js:958:69
    at new Promise (<anonymous>)
    at Object.error (/Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/@apollo/client/utilities/utilities.cjs.js:958:21)
    at notifySubscription (/Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/zen-observable/lib/Observable.js:140:18)
    at onNotify (/Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/zen-observable/lib/Observable.js:179:3)
    at SubscriptionObserver.error (/Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/zen-observable/lib/Observable.js:240:7)
    at /Users/micopanaga/Local Sites/nextjs/app/nextjs-wordpress-starter/node_modules/@apollo/client/utilities/utilities.cjs.js:946:68
    at Array.forEach (<anonymous>) {
  type: 'ApolloError',
  graphQLErrors: [],
  networkError: {
    name: 'ServerError',
    response: { size: 0, timeout: 0 },
    statusCode: 500,
    result: {
      code: 'internal_server_error',
      message: '<p>There has been a critical error on this website.</p><p><a href="https://wordpress.org/support/article/debugging-in-wordpress/">Learn more about debugging in WordPress.</a></p>',
      data: [Object],
      additional_errors: []
    }
  }
}
```

WP error logs shows this

```
[19-Feb-2021 14:11:30 UTC] PHP Fatal error:  Uncaught WPGraphQLGutenberg\Blocks\RegistryNotSourcedException: Client side block registry is missing. You need to open up gutenberg or load it from WPGraphQLGutenberg Admin page. in ~/nextjs/app/public/wp-content/plugins/wp-graphql-gutenberg/src/Blocks/Registry.php:41
Stack trace:
#0 ~/nextjs/app/public/wp-content/plugins/wp-graphql-gutenberg/src/Schema/Types/BlockTypes.php(253): WPGraphQLGutenberg\Blocks\Registry::get_registry()
#1 ~/nextjs/app/public/wp-includes/class-wp-hook.php(287): WPGraphQLGutenberg\Schema\Types\BlockTypes->WPGraphQLGutenberg\Schema\Types\{closure}(Object(WPGraphQL\Registry\TypeRegistry))
#2 ~/nextjs/app/public/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#3 ~/nextjs/app/public/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#4 ~/nextjs/app/public/wp-content/plugins/wp-graphql/src/Regis in ~/nextjs/app/public/wp-content/plugins/wp-graphql-gutenberg/src/Blocks/Registry.php on line 41
[19-Feb-2021 14:11:32 UTC] PHP Fatal error:  Uncaught WPGraphQLGutenberg\Blocks\RegistryNotSourcedException: Client side block registry is missing. You need to open up gutenberg or load it from WPGraphQLGutenberg Admin page. in ~/nextjs/app/public/wp-content/plugins/wp-graphql-gutenberg/src/Blocks/Registry.php:41
Stack trace:
#0 ~/nextjs/app/public/wp-content/plugins/wp-graphql-gutenberg/src/Schema/Types/BlockTypes.php(253): WPGraphQLGutenberg\Blocks\Registry::get_registry()
#1 ~/nextjs/app/public/wp-includes/class-wp-hook.php(287): WPGraphQLGutenberg\Schema\Types\BlockTypes->WPGraphQLGutenberg\Schema\Types\{closure}(Object(WPGraphQL\Registry\TypeRegistry))
#2 ~/nextjs/app/public/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#3 ~/nextjs/app/public/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#4 ~/nextjs/app/public/wp-content/plugins/wp-graphql/src/Regis in ~/nextjs/app/public/wp-content/plugins/wp-graphql-gutenberg/src/Blocks/Registry.php on line 41
[19-Feb-2021 14:12:18 UTC] PHP Fatal error:  Uncaught WPGraphQLGutenberg\Blocks\RegistryNotSourcedException: Client side block registry is missing. You need to open up gutenberg or load it from WPGraphQLGutenberg Admin page. in ~/nextjs/app/public/wp-content/plugins/wp-graphql-gutenberg/src/Blocks/Registry.php:41
Stack trace:
#0 ~/nextjs/app/public/wp-content/plugins/wp-graphql-gutenberg/src/Schema/Types/BlockTypes.php(253): WPGraphQLGutenberg\Blocks\Registry::get_registry()
#1 ~/nextjs/app/public/wp-includes/class-wp-hook.php(287): WPGraphQLGutenberg\Schema\Types\BlockTypes->WPGraphQLGutenberg\Schema\Types\{closure}(Object(WPGraphQL\Registry\TypeRegistry))
#2 ~/nextjs/app/public/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#3 ~/nextjs/app/public/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#4 ~/nextjs/app/public/wp-content/plugins/wp-graphql/src/Regis in ~/nextjs/app/public/wp-content/plugins/wp-graphql-gutenberg/src/Blocks/Registry.php on line 41
[19-Feb-2021 14:12:19 UTC] PHP Fatal error:  Uncaught WPGraphQLGutenberg\Blocks\RegistryNotSourcedException: Client side block registry is missing. You need to open up gutenberg or load it from WPGraphQLGutenberg Admin page. in ~/nextjs/app/public/wp-content/plugins/wp-graphql-gutenberg/src/Blocks/Registry.php:41
Stack trace:
#0 ~/nextjs/app/public/wp-content/plugins/wp-graphql-gutenberg/src/Schema/Types/BlockTypes.php(253): WPGraphQLGutenberg\Blocks\Registry::get_registry()
#1 ~/nextjs/app/public/wp-includes/class-wp-hook.php(287): WPGraphQLGutenberg\Schema\Types\BlockTypes->WPGraphQLGutenberg\Schema\Types\{closure}(Object(WPGraphQL\Registry\TypeRegistry))
#2 ~/nextjs/app/public/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#3 ~/nextjs/app/public/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#4 ~/nextjs/app/public/wp-content/plugins/wp-graphql/src/Regis in ~/nextjs/app/public/wp-content/plugins/wp-graphql-gutenberg/src/Blocks/Registry.php on line 41
```

I can fix this issue by going to WP Dashboard > GraphQL Gutenberg, then press "Update" button

<img width="1066" alt="Screen Shot 2021-02-19 at 10 20 57 PM" src="https://user-images.githubusercontent.com/5747475/108516982-ce67c200-7301-11eb-8eb4-6c9523138529.png">

We can probably add this in the Backend Wiki.

**To Reproduce**

1. Follow the Backend and Frontend Wiki steps.
2. Run `npm run dev` and see the error.

**Comment by gregrickaby** [comment]
I've mentioned this step in the [Backend Setup documentation](https://github.com/WebDevStudios/nextjs-wordpress-starter/wiki/Backend-Setup#update-wp-graphql-gutenberg). Thanks @donmhico
