### ISSUE TITLE
Few Issues - NPM RUN DEV and Redirects.

### ISSUE THREAD

**Issue by sloyer** [WebDevStudios/nextjs-wordpress-starter#334]
Hey there, I am really excited to dive into this more as we currently use Gatsby to consume WP but we really want to explore NEXT. 

I have followed the tutorial for front end to the T but I am having a few issues, the main thing is its causing the wordpress URL to error out "ERR_TOO_MANY_REDIRECTS".  

The second issue and the biggest issue is when i run 'npm run dev' I get 

```
`steve@Stevens-MacBook-Pro-2 NEXTJS % npm run dev

> nextjs-wordpress-starter@1.0.0 dev /Users/steve/NEXTJS
> npm run clean && next dev


> nextjs-wordpress-starter@1.0.0 clean /Users/steve/NEXTJS
> rimraf .next/

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /Users/steve/NEXTJS/.env
TypeError: Cannot read property 'split' of undefined
    at Object.<anonymous> (/Users/steve/NEXTJS/next.config.js:3:52)
    at Module._compile (internal/modules/cjs/loader.js:1075:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Function.Module._load (internal/modules/cjs/loader.js:781:14)
    at Module.require (internal/modules/cjs/loader.js:964:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at loadConfig (/Users/steve/NEXTJS/node_modules/next/dist/next-server/server/config.js:8:94)
    at async NextServer.loadConfig (/Users/steve/NEXTJS/node_modules/next/dist/server/next.js:1:2962)
    at async NextServer.prepare (/Users/steve/NEXTJS/node_modules/next/dist/server/next.js:1:2495)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nextjs-wordpress-starter@1.0.0 dev: `npm run clean && next dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nextjs-wordpress-starter@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Like it hates my .env file but im not sure why.

**Comment by sloyer** [comment]
My WP and .ENV file share the same tokens.

**Comment by sloyer** [comment]
Tried a Local copy of the WP site rather than using a digital ocean droplet same results produced. 

`steve@Stevens-MacBook-Pro-2 baileynext % node -v
v14.9.0
steve@Stevens-MacBook-Pro-2 baileynext % npm run dev

> nextjs-wordpress-starter@1.0.0 dev /Users/steve/baileynext
> npm run clean && next dev


> nextjs-wordpress-starter@1.0.0 clean /Users/steve/baileynext
> rimraf .next/

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
TypeError: Cannot read property 'split' of undefined
    at Object.<anonymous> (/Users/steve/baileynext/next.config.js:3:52)
    at Module._compile (internal/modules/cjs/loader.js:1075:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Function.Module._load (internal/modules/cjs/loader.js:781:14)
    at Module.require (internal/modules/cjs/loader.js:964:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at loadConfig (/Users/steve/baileynext/node_modules/next/dist/next-server/server/config.js:8:94)
    at async NextServer.loadConfig (/Users/steve/baileynext/node_modules/next/dist/server/next.js:1:2962)
    at async NextServer.prepare (/Users/steve/baileynext/node_modules/next/dist/server/next.js:1:2495)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nextjs-wordpress-starter@1.0.0 dev: `npm run clean && next dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nextjs-wordpress-starter@1.0.0 dev script.`

**Comment by gregrickaby** [comment]
@sloyer That's my fault. We refactored Next/Image support in #305, and I forgot to update both the `.env.sample` and Wiki with the new ENV Var we created.

You'll need to add the following (and replace with your URLs) to your `.env` file:

```text
NEXT_PUBLIC_IMAGE_DOMAINS="nextjs.wpengine.com, nextjsdevstart.wpengine.com, nextjswp.test"
```

See https://github.com/WebDevStudios/nextjs-wordpress-starter/blob/main/.env.sample#L33

**Comment by sloyer** [comment]
Awesome, that did the trick, excited to play around with this.  Gatsby plays really well with Gutenberg but I much prefer how Next handles a few things.

**Comment by sloyer** [comment]
an Unrelated note to this and I could be clueless, I am not seeing the "Additonal Settings" tab to set the 404 anywhere.

**Comment by sloyer** [comment]
And I just need to do the ACF Import. >.<
